---
- name: Normal playbook
  hosts: pvt
  become: yes
  gather_facts: yes
  become_user: root
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: print some stuff
      shell: |
        echo "Hello World"
        echo "This is a sample playbook"